apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jstrachan:
          repos:
            jx3-demo-gke-vault:
              required_status_checks:
                contexts:
                - promotion-build
            kubeconawesome:
              required_status_checks:
                contexts:
                - pr-build
            nodey504:
              required_status_checks:
                contexts:
                - pr-build
            nodey505:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/jx3-demo-gke-vault:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
      jstrachan/kubeconawesome:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/nodey504:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/nodey505:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
    presubmits:
      jstrachan/jx3-demo-gke-vault:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/kubeconawesome:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey504:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey505:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx3-demo-gke-vault: merge
        jstrachan/kubeconawesome: merge
        jstrachan/nodey504: merge
        jstrachan/nodey505: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-gke-vault
        - jstrachan/kubeconawesome
        - jstrachan/nodey504
        - jstrachan/nodey505
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-gke-vault
        - jstrachan/kubeconawesome
        - jstrachan/nodey504
        - jstrachan/nodey505
      target_url: http://deck-jx.35.238.123.29.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
