# Source: kubeconawesome/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-09-16T14:52:10Z"
  deletionTimestamp: null
  name: 'kubeconawesome-1.0.3'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        release 1.0.3
      sha: 6149850b31f9949c5438ab4d69902c8618c75993
    - author:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        release 1.0.3
      sha: 0f2afd7d8058a0543f8a62bb993dbb9436e65dd7
  gitCloneUrl: https://github.com/jstrachan/kubeconawesome.git
  gitHttpUrl: https://github.com/jstrachan/kubeconawesome
  gitOwner: jstrachan
  gitRepository: kubeconawesome
  name: 'kubeconawesome'
  releaseNotesURL: https://github.com/jstrachan/kubeconawesome/releases/tag/v1.0.3
  version: v1.0.3
status: {}
